name: Secure Blog Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    steps:
    - name: Clean Cache
      run: |
        rm -rf node_modules
        npm cache clean --force

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Inject API Token
      run: |
        sed -i "s/{{API_TOKEN}}/$API_TOKEN/g" *.html
        sed -i "s/wrongderra/${{ github.repository_owner }}/g" *.html
        sed -i "s/main/${GITHUB_REPOSITORY#*/}/g" *.html

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "public"
        retention-days: 1

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
